### ISSUE TITLE
HW1 tasks

### ISSUE THREAD

**Issue by Jcorrido** [Jcorrido/Homework1#1]
##### Tasks To Be Completed For HW1

- [x] **Upload** github profile picture

- [x] **Complete** Intro Sequence

- [x] **Complete** Ramping Up

- [x] **Complete** Moving Work Around

- [x] **Complete** A Mixed Bag
